language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env:
        - ENABLE_XDEBUG=true
    - php: 7.1
      env:
        - ENABLE_DEVTOOLS=true
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

os:
  - linux

notifications:
  irc: "chat.freenode.net#hoaproject"

sudo: false

env:
  global:
    - secure: "AAAAB3NzaC1yc2EAAAADAQABAAAAgQDLHtjDgygD/VkpGNUjUlwGDC1GHHx20eIdNwtxDdX5wS1Yt9OsAph4gUUJA+M2DAZEb6hETZ3tKojbEIrTF86c07yUWqerZ4+GfHdhAkrM3EQPDHxdoKRyoBOt45NnNlDqUuPDePDLauDxEwCUPGLNIf4IclAZbbJFPaeXsmaujw=="

cache:
  directories:
    - vendor/

before_script:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - if [[ ! $ENABLE_XDEBUG ]]; then
      phpenv config-rm xdebug.ini || echo "ext-xdebug is not available, cannot remove it.";
    fi

script:
  - composer install
  - vendor/bin/hoa test:run
  - if [[ $ENABLE_DEVTOOLS ]]; then
      composer global require friendsofphp/php-cs-fixer;
      vendor/bin/hoa devtools:cs --diff --dry-run .;
    fi
